In [19]:
import numpy as np
import torch as py


In [20]:
inputs = np.array([[73,67,43],
                    [91,88,64],
                    [87,134,58],
                    [102,43,37],
                    [69,96,70]], dtype='float32')

In [21]:
targets =np.array([[56,70],
            [81,101],
            [119,133],
            [22,37],
            [103,119]], dtype='float32')

In [22]:
inputs = py.from_numpy(inputs)
targets = py.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In the previous cell we converted the inputs and targets into tensors. In the next step we will be converting them into weights and biases. 

In [23]:
w = py.randn(2,3, requires_grad=True)
b = py.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.6667,  0.5289, -0.1211],
        [ 0.3630, -1.3854,  0.2881]], requires_grad=True)
tensor([-0.3459,  0.7215], requires_grad=True)


In [24]:
def model(ctx):
    return ctx@w.t() + b

In [25]:
predicts = model(inputs)
print(predicts)

tensor([[ -18.7823,  -53.2123],
        [ -22.2185,  -69.7209],
        [   5.5066, -136.6291],
        [ -50.0835,  -11.1659],
        [  -4.0471,  -87.0605]], grad_fn=<AddBackward0>)


In [26]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [27]:
def mse(d1,d2):
    diff = d1-d2
    return py.sum(diff*diff)/diff.numel()

In [28]:
loss = mse(predicts, targets)
print(loss)

tensor(20758.9922, grad_fn=<DivBackward0>)


In [29]:
loss.backward()

In [30]:
with py.no_grad():
    w -=w.grad * 1e-5
    b -=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [31]:
print(w)
print(b)

tensor([[-0.5877,  0.6143, -0.0680],
        [ 0.4972, -1.2229,  0.3843]], requires_grad=True)
tensor([-0.3450,  0.7232], requires_grad=True)


In [32]:
preds = model(inputs)
loss = mse(preds , targets)
print(loss)

tensor(14382.8184, grad_fn=<DivBackward0>)


For multiple epochs

In [33]:
for x in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with py.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [34]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(356.4371, grad_fn=<DivBackward0>)


In [35]:
preds

tensor([[ 57.8083,  78.5745],
        [ 78.9618, 107.3888],
        [125.0385, 104.3924],
        [ 24.7804,  84.4636],
        [ 94.0491, 103.2803]], grad_fn=<AddBackward0>)

In [36]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])